version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container-gestion-de-taches
    volumes:
      - ./www:/var/www/html
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container-gestion-de-taches
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container-gestion-de-taches
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
